# Generated by Django 4.2.5 on 2023-09-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Mscube MS3X', max_length=255)),
                ('quantity', models.IntegerField(default=50)),
                ('description', models.TextField(default='Puzzle rubik flagship oleh Mscube')),
                ('image', models.ImageField(upload_to='products/images/')),
            ],
        ),
    ]
